name: Hub
version: 1.3.0
api-version: 1.16
author: bk
main: net.pgfmc.hub.Main
description: Allows players to go to the Hub and other games
commands:
  goto:
    description: Teleport to a different world (please use /<world>)
    usage: /[world]
    aliases: [hub, survival, creative, prison, parkour]